Repository GDSC-Hongik/CodeReview-miyeok-server, pull requests merged in 2025-02, with the labels that each got.

#3 Chore: 프로젝트 초기 세팅
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/gdsc/codereview/CodereviewApplication.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ⚙ Setting

#9 Feat: RDS database 설정
  src/main/resources/application.yml
Labels: ⚙ Setting

#14 Feat: 인프런 강좌 도메인 및 크롤링 구현
  build.gradle
  driver/chromedriver.exe
  src/main/java/gdsc/codereview/domain/lecture/dto/LectureDto.java
  src/main/java/gdsc/codereview/domain/lecture/entity/Category.java
  src/main/java/gdsc/codereview/domain/lecture/entity/Lecture.java
  src/main/java/gdsc/codereview/domain/lecture/entity/Platform.java
  src/main/java/gdsc/codereview/domain/lecture/repository/LectureRepository.java
  src/main/java/gdsc/codereview/domain/lecture/service/InflearnCrawlingService.java
  src/main/java/gdsc/codereview/domain/lecture/service/LectureService.java
  src/main/java/gdsc/codereview/global/SeleniumConfig.java
  src/test/java/gdsc/codereview/domain/lecture/repository/LectureRepositoryTest.java
  src/test/java/gdsc/codereview/domain/lecture/service/InflearnCrawlingServiceTest.java
  src/test/resources/application.yml
Labels: ✨ Feature

#16 Feat: 인프런 강사 도메인 구현 및 크롤링 기능
  src/main/java/gdsc/codereview/domain/instructor/dto/InstructorDto.java
  src/main/java/gdsc/codereview/domain/instructor/entity/Instructor.java
  src/main/java/gdsc/codereview/domain/instructor/repository/InstructorRepository.java
  src/main/java/gdsc/codereview/domain/instructor/service/InstructorCrawlingService.java
  src/main/java/gdsc/codereview/domain/instructor/service/InstructorService.java
  src/main/java/gdsc/codereview/domain/lecture/dto/LectureDto.java
  src/main/java/gdsc/codereview/domain/lecture/entity/Category.java
  src/main/java/gdsc/codereview/domain/lecture/entity/Lecture.java
  src/main/java/gdsc/codereview/domain/lecture/service/InflearnCrawlingService.java
  src/main/java/gdsc/codereview/domain/review/dto/ReviewDto.java
  src/main/java/gdsc/codereview/domain/review/entity/Review.java
  src/main/java/gdsc/codereview/domain/review/repository/ReviewRepository.java
  src/main/java/gdsc/codereview/domain/review/service/ReviewCrawlingService.java
  src/main/java/gdsc/codereview/global/Platform.java
  src/test/java/gdsc/codereview/domain/instructor/service/InstructorCrawlingServiceTest.java
Labels: ✨ Feature

#21 Feat: swaggerdoc 연동
  build.gradle
  src/main/java/gdsc/codereview/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: ✨ Feature, 📃 Docs

#10 Feat: 구글 로그인 및 회원 관련 도메인 구현
  .gitignore
  build.gradle
  src/main/java/gdsc/codereview/domain/auth/controller/AuthController.java
  src/main/java/gdsc/codereview/domain/auth/dto/OAuthAttributes.java
  src/main/java/gdsc/codereview/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/gdsc/codereview/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/gdsc/codereview/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/gdsc/codereview/domain/auth/service/CustomUserDetails.java
  src/main/java/gdsc/codereview/domain/lecture/service/InflearnCrawlingService.java
  src/main/java/gdsc/codereview/domain/like/entity/Like.java
  src/main/java/gdsc/codereview/domain/like/entity/LikeType.java
  src/main/java/gdsc/codereview/domain/user/controller/UserController.java
  src/main/java/gdsc/codereview/domain/user/entity/OAuthType.java
  src/main/java/gdsc/codereview/domain/user/entity/Role.java
  src/main/java/gdsc/codereview/domain/user/entity/User.java
  src/main/java/gdsc/codereview/domain/user/repository/UserRepository.java
  src/main/java/gdsc/codereview/global/config/CorsConfig.java
  src/main/java/gdsc/codereview/global/config/RestTemplateConfig.java
  src/main/java/gdsc/codereview/global/config/SecurityConfig.java
  src/main/java/gdsc/codereview/global/config/SeleniumConfig.java
  src/main/java/gdsc/codereview/global/config/WebConfig.java
  src/main/resources/application.yml
Labels: ✨ Feature

#19 Feat: 데이터 리스트 api 구현
  src/main/java/gdsc/codereview/domain/instructor/controller/InstructorController.java
  src/main/java/gdsc/codereview/domain/instructor/dto/InstructorWithLectureDto.java
  src/main/java/gdsc/codereview/domain/instructor/repository/InstructorRepository.java
  src/main/java/gdsc/codereview/domain/instructor/service/InstructorService.java
  src/main/java/gdsc/codereview/domain/lecture/controller/LectureController.java
  src/main/java/gdsc/codereview/domain/lecture/dto/LectureDto.java
  src/main/java/gdsc/codereview/domain/lecture/dto/LectureReviewDto.java
  src/main/java/gdsc/codereview/domain/lecture/repository/LectureRepository.java
  src/main/java/gdsc/codereview/domain/lecture/service/LectureService.java
  src/main/java/gdsc/codereview/domain/review/dto/ReviewDto.java
  src/main/java/gdsc/codereview/domain/review/repository/ReviewRepository.java
Labels: 📬 API

#27 Feat/etc: 기타 추가사항들 구현
  src/main/java/gdsc/codereview/domain/lecture/controller/LectureController.java
  src/main/java/gdsc/codereview/domain/lecture/dto/LectureDto.java
  src/main/java/gdsc/codereview/domain/lecture/entity/Lecture.java
  src/main/java/gdsc/codereview/domain/lecture/repository/LectureRepository.java
  src/main/java/gdsc/codereview/domain/lecture/service/InflearnCrawlingService.java
  src/main/java/gdsc/codereview/domain/lecture/service/LectureService.java
Labels: ✨ Feature, 📬 API

#29 Feat: 강좌 비교 기능 구현
  src/main/java/gdsc/codereview/domain/auth/controller/AuthController.java
  src/main/java/gdsc/codereview/domain/gpt/service/ChatGPTService.java
  src/main/java/gdsc/codereview/domain/lecture/controller/LectureComparisonController.java
  src/main/java/gdsc/codereview/domain/lecture/dto/comparison/LectureComparisonRequestDto.java
  src/main/java/gdsc/codereview/domain/lecture/dto/comparison/LectureComparisonResponseDto.java
  src/main/java/gdsc/codereview/domain/lecture/dto/comparison/LectureSimpleResponseDto.java
  src/main/java/gdsc/codereview/domain/lecture/service/LectureComparisonService.java
  src/main/java/gdsc/codereview/domain/lecture/service/LectureService.java
  src/main/java/gdsc/codereview/domain/lecture/service/impl/LectureComparisonServiceImpl.java
  src/main/java/gdsc/codereview/global/config/ChatGPTConfig.java
  src/main/java/gdsc/codereview/global/config/RestTemplateConfig.java
  src/main/java/gdsc/codereview/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: ✨ Feature, 📬 API

#30 Feat: 로그인 수정 및 회원 정보 기능
  src/main/java/gdsc/codereview/domain/auth/controller/AuthController.java
  src/main/java/gdsc/codereview/domain/auth/converter/AuthConverter.java
  src/main/java/gdsc/codereview/domain/auth/dto/OAuthAttributes.java
  src/main/java/gdsc/codereview/domain/auth/jwt/JwtAccessDeniedHandler.java
  src/main/java/gdsc/codereview/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/gdsc/codereview/domain/auth/jwt/JwtAuthenticationHandler.java
  src/main/java/gdsc/codereview/domain/auth/jwt/JwtFilter.java
  src/main/java/gdsc/codereview/domain/auth/jwt/JwtProvider.java
  src/main/java/gdsc/codereview/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/gdsc/codereview/domain/auth/security/ExceptionFilter.java
  src/main/java/gdsc/codereview/domain/auth/security/GoogleClient.java
  src/main/java/gdsc/codereview/domain/auth/security/dto/GoogleProfile.java
  src/main/java/gdsc/codereview/domain/auth/security/dto/GoogleToken.java
  src/main/java/gdsc/codereview/domain/auth/service/AuthDetails.java
  src/main/java/gdsc/codereview/domain/auth/service/AuthDetailsService.java
  src/main/java/gdsc/codereview/domain/auth/service/AuthService.java
  src/main/java/gdsc/codereview/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/gdsc/codereview/domain/auth/service/SocialLoginService.java
  src/main/java/gdsc/codereview/domain/user/controller/UserController.java
  src/main/java/gdsc/codereview/domain/user/converter/UserConverter.java
  src/main/java/gdsc/codereview/domain/user/dto/request/IntroductionRequest.java
  src/main/java/gdsc/codereview/domain/user/dto/request/SignInRequest.java
  src/main/java/gdsc/codereview/domain/user/dto/request/UserInfoRequest.java
  src/main/java/gdsc/codereview/domain/user/dto/response/SignInResponse.java
  src/main/java/gdsc/codereview/domain/user/dto/response/TokenResponse.java
  src/main/java/gdsc/codereview/domain/user/dto/response/UserResponse.java
  src/main/java/gdsc/codereview/domain/user/entity/OAuthType.java
  src/main/java/gdsc/codereview/domain/user/entity/User.java
  src/main/java/gdsc/codereview/domain/user/repository/UserRepository.java
  src/main/java/gdsc/codereview/domain/user/service/UserService.java
  src/main/java/gdsc/codereview/global/config/CorsConfig.java
  src/main/java/gdsc/codereview/global/config/SecurityConfig.java
  src/main/java/gdsc/codereview/global/config/WebConfig.java
  src/main/java/gdsc/codereview/global/exception/ApiResponse.java
  src/main/java/gdsc/codereview/global/exception/BaseCode.java
  src/main/java/gdsc/codereview/global/exception/ExceptionResponse.java
  src/main/java/gdsc/codereview/global/exception/GeneralException.java
  src/main/java/gdsc/codereview/global/exception/ReasonDto.java
  src/main/java/gdsc/codereview/global/exception/status/ErrorStatus.java
  src/main/java/gdsc/codereview/global/exception/status/SuccessStatus.java
  src/main/resources/application.yml
Labels: ✨ Feature, 📬 API

#34 Feat: 마이페이지 / 강좌 즐겨찾기 / 리뷰 좋아요 및 싫어요 기능 구현
  src/main/java/gdsc/codereview/domain/favorite/controller/FavoriteController.java
  src/main/java/gdsc/codereview/domain/favorite/entity/Favorite.java
  src/main/java/gdsc/codereview/domain/favorite/repository/FavoriteRepository.java
  src/main/java/gdsc/codereview/domain/favorite/repository/FavoriteService.java
  src/main/java/gdsc/codereview/domain/like/controller/LikeController.java
  src/main/java/gdsc/codereview/domain/like/dto/CountResponseDto.java
  src/main/java/gdsc/codereview/domain/like/dto/LikeResponseDto.java
  src/main/java/gdsc/codereview/domain/like/entity/Like.java
  src/main/java/gdsc/codereview/domain/like/repository/LikeRepository.java
  src/main/java/gdsc/codereview/domain/like/service/LikeService.java
  src/main/java/gdsc/codereview/domain/review/controller/ReviewController.java
  src/main/java/gdsc/codereview/domain/review/dto/ReviewDto.java
  src/main/java/gdsc/codereview/domain/review/dto/ReviewResponseDto.java
  src/main/java/gdsc/codereview/domain/review/entity/Review.java
  src/main/java/gdsc/codereview/domain/review/repository/ReviewRepository.java
  src/main/java/gdsc/codereview/domain/review/service/ReviewService.java
  src/main/java/gdsc/codereview/global/exception/GlobalExceptionHandler.java
  src/main/resources/application.yml
Labels: ✨ Feature, 📬 API
